name: social_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.0
  stream_transform: ^2.0.0
  json_annotation: ^4.6.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  test: ^1.16.4

flutter:
  uses-material-design: true
